apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: default
  labels:
    app: ${{ values.name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ${{ values.name }}
