name: Setup CI/CD Automatically
on:
  workflow_dispatch:
    inputs:
      setup_required:
        description: 'Run setup (first time only)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  contents: read
  actions: write
  variables: write

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_required == 'true'
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Extract service name from package.json
        id: extract-name
        run: |
          # Try to get name from package.json, fallback to repository name
          if [ -f nodejs-microservice/package.json ]; then
            SERVICE_NAME=$(cat nodejs-microservice/package.json | jq -r '.name // empty')
          fi
          
          # If still empty, use repository name
          if [ -z "$SERVICE_NAME" ] || [ "$SERVICE_NAME" = "null" ]; then
            SERVICE_NAME="${{ github.repository }}"
            SERVICE_NAME="${SERVICE_NAME##*/}"  # Get just the repo name part
          fi
          
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "Using service name: $SERVICE_NAME"

      - name: Create ECR Repository
        run: |
          if ! aws ecr create-repository --repository-name ${{ steps.extract-name.outputs.service_name }} --region us-east-1; then
            echo "Repository already exists"
          fi

      - name: Set GitHub Variables
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          # Get the service name from the previous step
          SERVICE_NAME="${{ steps.extract-name.outputs.service_name }}"
          
          echo "Setting ECR_REPOSITORY variable to: $SERVICE_NAME"
          
          # Try to set the variable
          if gh variable set ECR_REPOSITORY --body "$SERVICE_NAME"; then
            echo "Variable set successfully with GH_ADMIN_TOKEN"
          else
            echo "Failed to set variable - needs to be set manually"
            echo "Command that failed: gh variable set ECR_REPOSITORY --body \"$SERVICE_NAME\""
          fi

      - name: Setup Complete
        run: |
          echo "✅ CI/CD Setup Complete!"
          echo "- ECR Repository: ${{ steps.extract-name.outputs.service_name }}"
          echo "- GitHub Variables: Configured"
          echo "- Ready for automatic deployments"

  info:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_required != 'true'
    steps:
      - name: Setup Info
        run: |
          echo "ℹ️  Setup already completed"
          echo "CI/CD is ready for deployments"
