name: Setup CI/CD Automatically
on:
  workflow_dispatch:
    inputs:
      setup_required:
        description: 'Run setup (first time only)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_required == 'true'
    permissions:
      contents: write
      actions: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Fix package.json name
        run: |
          # Replace template variables in package.json with actual repository name
          REPO_NAME="${{ github.repository }}"
          REPO_NAME="${REPO_NAME##*/}"  # Get just the repo name part
          if [ -f nodejs-microservice/package.json ]; then
            sed -i "s/\${{ values.name }}/$REPO_NAME/g" nodejs-microservice/package.json
            sed -i "s/\${{ values.description }}/Generated microservice for $REPO_NAME/g" nodejs-microservice/package.json
            echo "Updated package.json with repository name: $REPO_NAME"
          fi

      - name: Extract service name from package.json
        id: extract-name
        run: |
          # Try to get name from package.json, fallback to repository name
          if [ -f nodejs-microservice/package.json ]; then
            SERVICE_NAME=$(cat nodejs-microservice/package.json | jq -r '.name // empty')
          fi
          
          # If still empty, use repository name
          if [ -z "$SERVICE_NAME" ] || [ "$SERVICE_NAME" = "null" ]; then
            SERVICE_NAME="${{ github.repository }}"
            SERVICE_NAME="${SERVICE_NAME##*/}"  # Get just the repo name part
          fi
          
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "Using service name: $SERVICE_NAME"
          
      - name: Create ECR repository if not exists
        run: |
          aws ecr create-repository --repository-name $REPO_NAME --region us-east-1 || echo "Repository already exists"
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REPO_NAME: ${{ steps.extract-name.outputs.service_name }}
          
      - name: Set GitHub Variables
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          echo "Testing token permissions first..."
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}
          
          echo "Creating variables with direct API calls..."
          
          # Create variables using GitHub API directly
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            -d "{\"name\":\"ECR_REPOSITORY\",\"value\":\"${{ steps.extract-name.outputs.service_name }}\"}" || echo "Variable may already exist"
          
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            -d "{\"name\":\"APP_NAME\",\"value\":\"${{ steps.extract-name.outputs.service_name }}\"}" || echo "Variable may already exist"
          
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            -d "{\"name\":\"ECR_REGISTRY\",\"value\":\"124213954422.dkr.ecr.us-east-1.amazonaws.com\"}" || echo "Variable may already exist"
          
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            -d "{\"name\":\"AWS_REGION\",\"value\":\"us-east-1\"}" || echo "Variable may already exist"
          
      - name: Setup Complete
        run: |
          echo "✅ CI/CD Setup Complete!"
          echo "- ECR Repository: ${{ steps.extract-name.outputs.service_name }}"
          echo "- GitHub Variables: Configured automatically"
          echo "- AWS Region: us-east-1"
          echo "- Ready for automatic deployments!"

  info:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_required != 'true'
    steps:
      - name: Setup Info
        run: |
          echo "ℹ️  Setup already completed"
          echo "CI/CD is ready for deployments"
