name: Setup CI/CD Automatically
on:
  workflow_dispatch:
    inputs:
      setup_required:
        description: 'Run setup (first time only)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_required == 'true'
    permissions:
      contents: write
      actions: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Extract service name from package.json
        id: extract-name
        run: |
          SERVICE_NAME=$(cat package.json | jq -r '.name')
          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          
      - name: Create ECR Repository
        run: |
          aws ecr create-repository --repository-name ${{ steps.extract-name.outputs.service_name }} --region us-east-1 || echo "Repository already exists"
          
      - name: Set GitHub Variables
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh variable set ECR_REPOSITORY --body "${{ steps.extract-name.outputs.service_name }}"
          gh variable set APP_NAME --body "${{ steps.extract-name.outputs.service_name }}"
          gh variable set ECR_REGISTRY --body "124213954422.dkr.ecr.us-east-1.amazonaws.com"
          gh variable set AWS_REGION --body "us-east-1"
          
      - name: Setup Complete
        run: |
          echo "✅ CI/CD Setup Complete!"
          echo "- ECR Repository: ${{ steps.extract-name.outputs.service_name }}"
          echo "- GitHub Variables: Configured automatically"
          echo "- AWS Region: us-east-1"
          echo "- Ready for automatic deployments!"

  info:
    runs-on: ubuntu-latest
    if: github.event.inputs.setup_required != 'true'
    steps:
      - name: Setup Info
        run: |
          echo "ℹ️  Setup already completed"
          echo "CI/CD is ready for deployments"
